### PR TITLE
Add binarySearch in 2D row column wise sorted matrix

### PR DESCRIPTION
**Pull request by siddharthav19**

### CODE REVIEW

**Comment by ritik-369** [comment]
code is not completed

**Comment by ritik-369** [comment]
also write some comments in it

**Comment by siddharthav19** [comment]
> also write some comments in it

Ok will do it and update it

**Comment by ritik-369** [comment]
Yes🙂

**Comment by siddharthav19** [comment]
> Yes🙂

done

**Review by siddharthav19 — COMMENTED** [review]
commented and implemented an example

**Review by ritik-369 — APPROVED** [review]

**Pull request merged**
